SELECT * FROM customer_behaviour_analysis


--------------------------------------------------------------------------------------
-- Business Insights Questions
--------------------------------------------------------------------------------------

--Q1. Which category generates highest revenue?
SELECT category, ROUND(SUM(purchase_amount_usd)::NUMERIC,2) AS highest_revenue 
FROM customer_behaviour_analysis
GROUP BY category
ORDER BY highest_revenue DESC
--Ans: Electronics category generate highest revenue

--Q2. Are discounts actually increasing purchase value?
SELECT discount_applied, 
	ROUND(SUM(purchase_amount_usd)::numeric, 2) AS total_revenue,
	ROUND(AVG(purchase_amount_usd)::numeric, 2) AS avg_purchase
FROM customer_behaviour_analysis
GROUP BY discount_applied
--Ans: No, the discount applied orders doesn't incerase purchase value.

--Q3. What is the total revenue generated by male and female customer?
SELECT gender, ROUND(SUM(purchase_amount_usd)::numeric, 2) AS total_revenue
FROM customer_behaviour_analysis
GROUP BY gender
ORDER BY total_revenue DESC
--Ans: Male gender generates highest revenue.

--Q4. Which customer used a discount but still spent more than the avg. purchase amount?
SELECT customer_id, purchase_amount_usd, discount_applied
FROM customer_behaviour_analysis
WHERE discount_applied='Yes' AND 
purchase_amount_usd > (SELECT AVG(purchase_amount_usd) FROM customer_behaviour_analysis)
ORDER BY purchase_amount_usd desc LIMIT 10
--Ans: These are the high spending customer who are also discount users.

--Q5. Which are the top/bottom 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating)::NUMERIC, 2) AS avg_ratings
FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY avg_ratings DESC LIMIT 5

SELECT item_purchased, ROUND(AVG(review_rating)::NUMERIC, 2) AS avg_ratings
FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY avg_ratings LIMIT 5
--Ans: Clear understanding of product performance based on customer satisfaction.

--Q6. Average purchase: Standard vs Express shipping
SELECT shipping_type, COUNT(DISTINCT customer_id) AS order_placed, 
	ROUND(AVG(purchase_amount_usd)::numeric,2) AS avg_purchase,
	ROUND(SUM(purchase_amount_usd)::numeric, 2) AS revenue
FROM customer_behaviour_analysis
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
--Ans: Overall, express generate highest revenue than standard. But there is not significant differences.

--Q7. Do subscribed customers spend more? Compare avg. spend and total revenue between subscribers & non-subcribers.
SELECT  subscription_status,
	COUNT(customer_id) AS users,
	ROUND(AVG(purchase_amount_usd)::numeric, 2) AS avg_revenue,
	ROUND(SUM(purchase_amount_usd)::numeric, 2) AS total_revenue
FROM customer_behaviour_analysis
GROUP BY subscription_status
ORDER BY total_revenue DESC
--Ans: Yes, but non-subscriber generate more revenue than subscriber customer.

--Q8. Top 5 products with highest discount usage %
SELECT item_purchased,
	COUNT(item_purchased) AS total_number_of_times_sold,
	COUNT(CASE WHEN discount_applied='Yes' THEN 1 END) AS number_of_times_sold_when_discount_applied,
	ROUND(COUNT(CASE WHEN discount_applied='Yes' THEN 1 END)*100.0/COUNT(*)::NUMERIC, 2) AS discount_percent
FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY discount_percent DESC
LIMIT 5
--Ans: Laptop, phone, headphones, hat and watch items are purchase around 50% when discount is available 


--Q9. Segment customer into new, returning and loyal based on their total number of previous purchase,
--and show the count of each segment.
SELECT 
	CASE 
		WHEN previous_purchases='0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END AS customer_segment,
COUNT(*) AS customer_count
FROM customer_behaviour_analysis
GROUP BY CASE
		WHEN previous_purchases='0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END
ORDER BY customer_count DESC
--Ans: Now, we can make personlised marketing and improves retention strategies.

--Q10. What are the top 3 most purchased products wihtin each category?
WITH CTE AS
(SELECT category, item_purchased,
	COUNT(item_purchased) AS most_purchased,
	RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
FROM customer_behaviour_analysis
GROUP BY category, item_purchased
)
SELECT * FROM CTE WHERE RNK<=3
--Ans: Now, campany knows what are the top 3 product within different category.


